### PR TITLE
Support PHPStan 2.0

### PR DESCRIPTION
**Pull request by spaze**

### CODE REVIEW

**Comment by spaze** [comment]
This adds support for PHPStan 2.0, feel free to release whenever you like :-)

**Comment by spaze** [comment]
Hey @turbo124 @anthonyryan1 would you like to create a release? Or should I do it? :-)

**Comment by turbo124** [comment]
@spaze I am happy to tag this, looks like a minor version release.

**Comment by spaze** [comment]
Cool @turbo124 Yeah, doesn't need to be major, no breaking stuff, hopefully. Thanks!

**Pull request merged**
